### ISSUE TITLE
Cannot invoke "java.util.List.iterator()" because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null

### ISSUE THREAD

**Issue by ookk36930** [Aeldit/CyanSetHome#3]
when i use /sh 1

Cannot invoke "java.util.List.iterator()"
because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null

**Comment by ookk36930** [comment]
MC version 1.20.4

**Comment by Aeldit** [comment]
I'll check that when I get home. 

Which version of cyansh are you using?

**Comment by ookk36930** [comment]
[1.20.4] CyanSetHome 0.1.7
v9.0.0 for 1.20.4
[1.20.4] CyanLib 0.4.9

**Comment by Aeldit** [comment]
Thanks, I'll investigate this this weekend and come back to you when I find the issue

**Comment by Aeldit** [comment]
The issue is fixed, I'm gonna fix it for every other version and they will be available on Modrinth soon
